name: "Get and Cache Dependencies"
description: "Get the Dependencies (from npm) and cache them"
runs:
  using: "composite"
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashfiles('**/package-lock.json')}}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
